name: flutter_basic_quickstart
description: Flutter Basic Quickstart
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.2
  vector_graphics: ^1.1.2
  flutter_native_splash: ^2.3.8
  flutter_riverpod: ^2.3.0
  flutter_hooks: ^0.20.3
  google_fonts: ^6.1.0
  icons_launcher: ^2.1.0
  go_router: ^13.0.0
  path: ^1.8.3
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  go_router_builder: ^2.0.1
  build_runner: ^2.3.3
  vector_graphics_compiler: ^1.1.2

flutter_native_splash:
  android: true
  ios: true
  image: "raw_assets/png/splashImage.png"
  background_image: "raw_assets/png/splashBackground.png"

flutter:
  uses-material-design: true
  assets:
    # Fonts
    - "assets/google_fonts/"
    # Images
    - assets/images/magicPot.svg.vec
